url=https://www.google.com
urlTest=https://opensource-demo.orangehrmlive.com/
browser=chrome
Username=Admin
Pswd=admin123
driverLocation=C:\\Users\\hachiluk\\OneDrive - Capgemini\\Desktop\\My Automation\\chromedriver-win64\\chromedriver-win64\\chromedriver.exe
FN=abg45
MN=f12
LN=g22